/*
Project Java Form ini bertujuan untuk mengimplementasikan project dari laporan project work dengan mengumpulkan ilmu-ilmu yang didapat selama ini dan mengimplementasikan di satu project besar.
*/

// Author : Passcape (E:)


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package Main;


import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Passcape
 */

public class fKasir extends javax.swing.JFrame {

    String namaPerusahaan = "PT. MAJU BERSAMA";

    boolean firstTime = true;
    boolean isRunning = true;
    boolean exitAuth = false;

    String currentUser;
    String latestUser;

    DecimalFormat dec = new DecimalFormat("###,###");

    static ArrayList<String> item = new ArrayList<>();
    static ArrayList<String> code = new ArrayList<>();
    static ArrayList<Integer> price = new ArrayList<>();

    static ArrayList<String> user = new ArrayList<>();
    static ArrayList<String> pass = new ArrayList<>();
    static ArrayList<String> cName = new ArrayList<>();

    String[] MaintblHeader = {"NAMA BARANG", "KUANTITAS"};
    DefaultTableModel maindtm = new DefaultTableModel(MaintblHeader, 0);

    String[] HistorytblHeader = {"TIME", "CASHIER NAME", "ITEM NAME", "QUANTITY"};
    DefaultTableModel historydtm = new DefaultTableModel(HistorytblHeader, 0);

    private static void addItem(String kodeBarang, String namaBarang, int hargaBarang) {
        code.add(kodeBarang.toUpperCase());
        item.add(namaBarang.toUpperCase());
        price.add(hargaBarang);
    }

    private static void auth(String username, String password, String cashierName) {
        user.add(username);
        pass.add(password);
        cName.add(cashierName.toUpperCase());
    }

    private String time() {
        LocalDateTime date = LocalDateTime.now();
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        return dateFormat.format(date);
    }

    /**
     * Creates new form fKasir
     */

    public fKasir() {
        initComponents();
        JTabbedPane1.setSelectedIndex(0);
        JTabbedPane1.setEnabledAt(0, false);
        JTabbedPane1.setEnabledAt(1, false);
        MaintblMain.setModel(maindtm);
        MaintblMain.setDefaultEditor(Object.class, null);
        HistorytblHistory.setDefaultEditor(Object.class, null);
        HistorytblHistory.setModel(historydtm);

        Timer delay;
        delay = new Timer(1000, (ActionEvent e) -> {
            LoginlblTime.setText(time());
            MainlblTime.setText(time());
            HistorylblTime.setText(time());
        });
        if (isRunning) {
            delay.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTabbedPane1 = new javax.swing.JTabbedPane();
        paneLogin = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        LoginbtnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        LoginlblTime = new javax.swing.JLabel();
        paneMain = new javax.swing.JPanel();
        txtHarga = new javax.swing.JTextField();
        txtKuantitas = new javax.swing.JTextField();
        txtHargaTotal = new javax.swing.JTextField();
        btnTambahkanItem = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAddQty = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnInvoice = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        btnLogOut = new javax.swing.JButton();
        txtNamaBarang = new javax.swing.JTextField();
        btnDeQty = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MaintblMain = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        MainlblTime = new javax.swing.JLabel();
        paneHistory = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistorytblHistory = new javax.swing.JTable();
        HistorybtnBack = new javax.swing.JButton();
        HistorylblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasirris");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        JTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        JTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        JTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTabbedPane1.setEnabled(false);

        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        pwdPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setText("User");

        jLabel7.setText("Password");

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setMnemonic('L');
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        LoginbtnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginbtnClear.setMnemonic('C');
        LoginbtnClear.setText("CLEAR");
        LoginbtnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setMnemonic('E');
        btnExit.setText("EXIT");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        LoginlblTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginlblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout paneLoginLayout = new javax.swing.GroupLayout(paneLogin);
        paneLogin.setLayout(paneLoginLayout);
        paneLoginLayout.setHorizontalGroup(
            paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLoginLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(paneLoginLayout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoginbtnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit))
                    .addComponent(pwdPassword)
                    .addComponent(txtUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 766, Short.MAX_VALUE)
                .addComponent(LoginlblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        paneLoginLayout.setVerticalGroup(
            paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLoginLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LoginlblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(LoginbtnClear)
                    .addComponent(btnExit))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        JTabbedPane1.addTab("Login", paneLogin);

        txtHarga.setEditable(false);
        txtHarga.setText(" ");

        txtKuantitas.setText("1");

        txtHargaTotal.setEditable(false);
        txtHargaTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtHargaTotal.setText("0");
        txtHargaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaTotalActionPerformed(evt);
            }
        });

        btnTambahkanItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambahkanItem.setText("TAMBAHKAN ITEM");
        btnTambahkanItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahkanItemActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAddQty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddQty.setText("ADD QTY");
        btnAddQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQtyActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setText("CARI ITEM");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnInvoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInvoice.setText("INVOICE");
        btnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Kode Barang");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama Barang");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Kuantitas");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Harga Total");

        txtKodeBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKodeBarangMouseClicked(evt);
            }
        });
        txtKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeBarangActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogOut.setText("LOG OUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        txtNamaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNamaBarangMouseClicked(evt);
            }
        });

        btnDeQty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeQty.setText("DE-QTY");
        btnDeQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeQtyActionPerformed(evt);
            }
        });

        btnHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHistory.setText("HISTORY");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        MaintblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "NAMA BARANG", "KUANTITAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MaintblMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MaintblMain.setShowHorizontalLines(true);
        MaintblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaintblMainMouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(MaintblMain);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Bayar");

        txtBayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Kembalian");

        txtKembalian.setEditable(false);
        txtKembalian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtKembalian.setText("0");
        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername.setText("Nama Kasir");

        MainlblTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MainlblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout paneMainLayout = new javax.swing.GroupLayout(paneMain);
        paneMain.setLayout(paneMainLayout);
        paneMainLayout.setHorizontalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneMainLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(paneMainLayout.createSequentialGroup()
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paneMainLayout.createSequentialGroup()
                                .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(paneMainLayout.createSequentialGroup()
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(paneMainLayout.createSequentialGroup()
                                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnDeQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAddQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(btnTambahkanItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                            .addComponent(btnInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MainlblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );
        paneMainLayout.setVerticalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(MainlblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(paneMainLayout.createSequentialGroup()
                            .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(paneMainLayout.createSequentialGroup()
                                    .addComponent(btnAddQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDeQty, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnTambahkanItem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(paneMainLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(6, 6, 6)
                            .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtKuantitas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMainLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMainLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMainLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );

        JTabbedPane1.addTab("Main", paneMain);

        HistorytblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Time", "Cashier Name", "Item Name", "Item Quantity"
            }
        ));
        HistorytblHistory.setShowGrid(true);
        jScrollPane1.setViewportView(HistorytblHistory);

        HistorybtnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HistorybtnBack.setText("BACK");
        HistorybtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorybtnBackActionPerformed(evt);
            }
        });

        HistorylblTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HistorylblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout paneHistoryLayout = new javax.swing.GroupLayout(paneHistory);
        paneHistory.setLayout(paneHistoryLayout);
        paneHistoryLayout.setHorizontalGroup(
            paneHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
            .addGroup(paneHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HistorybtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HistorylblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        paneHistoryLayout.setVerticalGroup(
            paneHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHistoryLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(paneHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HistorybtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HistorylblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        JTabbedPane1.addTab("History", paneHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JTabbedPane1.getAccessibleContext().setAccessibleName("Form");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeBarangActionPerformed

    }//GEN-LAST:event_txtKodeBarangActionPerformed

    private void txtKodeBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKodeBarangMouseClicked
        txtNamaBarang.setEditable(false);
        txtKodeBarang.setEditable(true);
        txtNamaBarang.setText("");
    }//GEN-LAST:event_txtKodeBarangMouseClicked

    private void txtNamaBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNamaBarangMouseClicked
        txtKodeBarang.setEditable(false);
        txtNamaBarang.setEditable(true);
        txtKodeBarang.setText("");
    }//GEN-LAST:event_txtNamaBarangMouseClicked

    private void btnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceActionPerformed
        ArrayList<String> nBenda = new ArrayList<>();

        for (int i = 0; i >= maindtm.getRowCount() + 1; i++) {
            nBenda.add(String.valueOf(maindtm.getValueAt(i, i)) + "*" + String.valueOf(maindtm.getValueAt(i, i + 1)) + "\n");
        }

        JOptionPane.showMessageDialog(this, namaPerusahaan + "\n" + time() + "\n================================\n" + Arrays.toString(nBenda.toArray()) + "\nTotal     : " + txtHargaTotal.getText()
                + "\nBayar     : " + dec.format(Integer.valueOf(txtBayar.getText())) + "\nKembalian : " + txtKembalian.getText(), "INVOICE", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnInvoiceActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int logOutConfirmation = JOptionPane.showConfirmDialog(this, "This session will be logged out\nAre you sure?", "Log Out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (logOutConfirmation == 0) {
            System.out.println(time() + " | " + currentUser + " telah logout.");
            JOptionPane.showMessageDialog(this, "Logged Out.", "Log Out", JOptionPane.INFORMATION_MESSAGE);
            btnClear.doClick();
            currentUser = "";
            lblUsername.setText("");
            JTabbedPane1.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "Log Out Cancelled.", "Log Out", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try {
            if (txtNamaBarang.getText().isBlank()) {
                int index = code.indexOf(txtKodeBarang.getText());
                txtNamaBarang.setText(item.get(index));
                txtHarga.setText(dec.format(price.get(index)));
            } else {
                int index = item.indexOf(txtNamaBarang.getText().toUpperCase());
                txtKodeBarang.setText(code.get(index));
                txtHarga.setText(dec.format(price.get(index)));
            }
        } catch (IndexOutOfBoundsException e) {
            if (txtNamaBarang.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Kode Barang tidak ditemukan.", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Nama Barang tidak ditemukan.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnCariActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtKodeBarang.setText("");
        txtNamaBarang.setText("");
        txtHarga.setText("");
        txtKuantitas.setText("1");
        txtHargaTotal.setText("0");
        txtBayar.setText("");
        txtKembalian.setText("0");
        for (int i = maindtm.getRowCount(); 0 < maindtm.getRowCount(); i--) {
            maindtm.removeRow(i - 1);
        }
        firstTime = false;
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQtyActionPerformed
        int qty = Math.abs(Integer.parseInt(txtKuantitas.getText()) + 1);
        txtKuantitas.setText(String.valueOf(qty));
    }//GEN-LAST:event_btnAddQtyActionPerformed

    private void btnDeQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeQtyActionPerformed
        int qty = Math.abs(Integer.parseInt(txtKuantitas.getText()) - 1);
        txtKuantitas.setText(String.valueOf(qty));
    }//GEN-LAST:event_btnDeQtyActionPerformed

    private void LoginbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnClearActionPerformed
        txtUser.setText("");
        pwdPassword.setText("");
    }//GEN-LAST:event_LoginbtnClearActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            UIManager.put("Button.defaultButtonFollowFocus", Boolean.TRUE);
            int index = user.indexOf(txtUser.getText());
            if (txtUser.getText().equals(user.get(index)) && pwdPassword.getText().equals(pass.get(index))) {
                currentUser = cName.get(user.indexOf(txtUser.getText()));
                latestUser = currentUser;
                System.out.println(time() + " | " + currentUser + " telah login.");
                txtUser.setText("");
                pwdPassword.setText("");
                lblUsername.setText("Cashier Name : " + currentUser);
                JOptionPane.showMessageDialog(this, "Access Granted.", "Login", JOptionPane.INFORMATION_MESSAGE);
                JTabbedPane1.setSelectedIndex(1);
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Username or Password!", "Login", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Incorrect Username or Password!", "Login", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        try {
            String exitConfirmation = JOptionPane.showInputDialog(this, "Input the password to proceed.\n(Ask the supervisor/manager/chief)", "Exit", JOptionPane.QUESTION_MESSAGE);
            if (exitConfirmation.equals("123")) {
                exitAuth = true;
                System.out.println(time() + " | " + latestUser + " telah keluar dari aplikasi.");
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Password!", "Exit", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Exit Cancelled.", "Exit", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        JTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void txtHargaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaTotalActionPerformed

    private void HistorybtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorybtnBackActionPerformed
        JTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_HistorybtnBackActionPerformed

    private void btnTambahkanItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahkanItemActionPerformed
        if (!txtKodeBarang.getText().isBlank() && !txtNamaBarang.getText().isBlank() && !txtKuantitas.getText().isBlank() && Integer.parseInt(txtKuantitas.getText()) > 0) {
            LocalDateTime date = LocalDateTime.now();
            DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
            String[] row = {txtNamaBarang.getText().toUpperCase(), txtKuantitas.getText()};
            maindtm.addRow(row);
            String[] history = {dateFormat.format(date), currentUser, txtNamaBarang.getText().toUpperCase(), txtKuantitas.getText()};
            historydtm.addRow(history);
            System.out.println(time() + " | " + currentUser + " menambahkan " + txtNamaBarang.getText().toUpperCase() + "(" + txtKodeBarang.getText() + ")");
            int hargaTotal = Integer.parseInt(txtHargaTotal.getText().replace(".", ""));
            int harga = Integer.parseInt(txtHarga.getText().replace(".", ""));
            int kuantitas = Integer.parseInt(txtKuantitas.getText());
            hargaTotal += (harga * kuantitas);
            txtHargaTotal.setText(dec.format(hargaTotal));
        } else {
            JOptionPane.showMessageDialog(this, "Ada kesalahan pada data!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahkanItemActionPerformed

    private void MaintblMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaintblMainMouseExited

    }//GEN-LAST:event_MaintblMainMouseExited

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int index = MaintblMain.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Pilih salah satu item di Tabel!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            int hargaTotal = Integer.parseInt(txtHargaTotal.getText().replace(".", ""));
            int harga = price.get(item.indexOf(maindtm.getValueAt(index, 0)));
            int kuantitas = Integer.parseInt(String.valueOf(maindtm.getValueAt(index, 1)));
            hargaTotal -= (harga * kuantitas);
            maindtm.removeRow(index);
            if (firstTime) {
                historydtm.removeRow(index);
            } else {
                historydtm.removeRow(((historydtm.getRowCount() - 1) - maindtm.getRowCount()) + index);
            }
            txtHargaTotal.setText(dec.format(hargaTotal));
            System.out.println(time() + " | " + currentUser + " mengurangi " + txtNamaBarang.getText().toUpperCase() + "(" + txtKodeBarang.getText() + ")");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        btnExit.doClick();
        if (exitAuth) {
            System.exit(0);
        } else {
            for (int i = 1; i <= 10; i++) {
                JOptionPane.showMessageDialog(this, "You're not allowed to exit!", "Exir", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        try {
            int hargaTotal = Integer.parseInt(txtHargaTotal.getText().replace(".", ""));
            int bayar = Integer.parseInt(txtBayar.getText());

            if (bayar >= hargaTotal) {
                txtKembalian.setText(dec.format(bayar - hargaTotal));
            } else {
                JOptionPane.showMessageDialog(this, "Uang kurang untuk pembayaran ini!", "PERINGATAN", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mohon input data secara benar!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Mohon input bayar!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtBayarActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //CONSTANT :

        //Data User Disini :
        auth("admin", "admin1234", "ADMIN");
        auth("faratputri", "fptri2324", "Farat Putri");
        auth("jokowarwir72", "12345678", "Joko Warwir");

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
//untuk menangkap jika adanya CNF Exception
            java.util.logging.Logger.getLogger(fKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            //Buat method setVisible() ini selalu true!
            public void run() {
                new fKasir().setVisible(true);
            }
        });

        // Tambahkan Data Item Disini : (kode_barang, nama_barang, harga_barang)
        addItem("143276", "DUNHILL HTM 16", 32500);
        addItem("735907", "VEEV DPS GRAPE", 80000);
        addItem("613879", "ALKALINE AAA", 15000);
        addItem("036783", "SPIDOL SNOWMAN BG12 HITAM", 12700);
        addItem("615644", "GATSBY CLAY MATTE FINISH 80G", 45000);
        addItem("262347", "MURRAYS POMADE 85G", 83500);
        addItem("486818", "JOYKO CT522PTL 12MX5MM", 11200);
        addItem("031614", "CLORIS MEN SUNSCREEN 50ML", 56900);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HistorybtnBack;
    private javax.swing.JLabel HistorylblTime;
    private javax.swing.JTable HistorytblHistory;
    private javax.swing.JTabbedPane JTabbedPane1;
    private javax.swing.JButton LoginbtnClear;
    private javax.swing.JLabel LoginlblTime;
    private javax.swing.JLabel MainlblTime;
    private javax.swing.JTable MaintblMain;
    private javax.swing.JButton btnAddQty;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeQty;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnInvoice;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnTambahkanItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel paneHistory;
    private javax.swing.JPanel paneLogin;
    private javax.swing.JPanel paneMain;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHargaTotal;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtKuantitas;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
